apiVersion: v1
kind: Namespace
metadata:
  name: spinnaker

---
apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: halyard-local-path-pvc 
  namespace: spinnaker
spec: 
  accessModes: 
  - ReadWriteOnce 
  resources: 
    requests:
      storage: 100Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: halyard-deploy
 namespace: spinnaker
spec:
 replicas: 1
 selector:
  matchLabels:
   app: halyard
 template:
  metadata:
   name: halyard-template
   labels:
    app: halyard
  spec:
   containers:
   - name: halyard
     image: us-docker.pkg.dev/spinnaker-community/docker/halyard:stable
     volumeMounts:
     - mountPath: "/home/spinnaker/.hal/"
       name: halyard-vol
       subPath: "spinnaker/.hal/"
     - mountPath: "/home/spinnaker/.kube/"
       name: halyard-kubeconfig-vol
   volumes:
   - name: halyard-kubeconfig-vol
     configMap:
       name: halyard-kubeconfig
   - name: halyard-vol
     persistentVolumeClaim:
       claimName: halyard-local-path-pvc 

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: halyard-kubeconfig
  namespace: spinnaker
data:
  config: |-
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1EZ3hOREl3TWpBME5Wb1hEVE14TURneE1qSXdNakEwTlZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSmlPCjJObGVUUWZHUGNqTWJHcGhSaElsQXFqa01SYkVua0xHcWZUWDJHNXh4YjR5cjJIWkdhWUt3dWlCSk1UTmYwU1EKeFZFakdoM2tRTzllTXlEa2k2VGlMOUdUQUpTRG1ZWXBVYWZjNE0xU2ZyZldkZ2MwUXE0VmhtS3lUUjN3VmRtNQovUGk4aEtpY3k2NjAzMW5qOG1KeXd3NFNxYU5ybFRYRDBpNjdVUm5OeXY2WkdmL0wwSEdOUEJsZ2tSNDhPNE5ZCmJhZ3lMMEhYRkdKellqcVFreHN1ZVJmYVRmem5obW5sVkxSRnJOQTZ6MTd2NVJyNHZTRFdpTWNMY21vZzZVOUEKZXdKamx0Vll1TmlKTlRHWE1kYVVMZUJ0YW1NemVnaytGcXN0M2ErNEJMOW5NNlpReERYQWQ1d3Q5WWFmTWNtQQpSOGZDRkVnZjUwN3RXS29kS3hzQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZGREpWc3NIcWlaZ09xWlJ1TkhHeHdnZ29GTTNNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQlVzSTA1czV6MWhzcjNVcnlKegpjL245eHBHekVIQVd2WmE0OXRoM1FxVytnQ1BicFFhRVplMmpQbS9IWFh1R01NTHFiUFZQVHhDZHhLNnNnRHVqCnN0UDNUQmFwR3hYVXRZZUxuNGk4OHpwSzhUdFRHSEVCZlUycFBmOGlteVJlZDY4ekpnV2pPOUJabnJlRnUrckEKUHMrQVVLcVBHeGptS1FmcWNHRXIwS0YxRGtMR3o0S1hrckx1NzhwQkdYZUdGTjAxdGtseTU4MlREUVFaVStLawpKaU9DWXo3ekZtMlh1OU1sRG8rWXMxWW1pZEUzbkF2dFlSQlA1Wkp6cU50T0kxZXNFOE1SWUUvYlVUaEpiNGh3CjdNdGFubkwwUjl5Sy9aWndYY0lZR1VRbkR0WDBtbHIra05rV00yZ1pFSSswYmhtMGVyMHRsUjIxVm1jMmliWmYKMUpvPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        server: https://192.168.100.210:6443
      name: kubernetes
    contexts:
    - context:
        cluster: kubernetes
        user: kubernetes-admin
      name: kubernetes-admin@kubernetes
    current-context: kubernetes-admin@kubernetes
    kind: Config
    preferences: {}
    users:
    - name: kubernetes-admin
      user:
        client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lJRzlocjBkWHVsdWd3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TVRBNE1UUXlNREl3TkRWYUZ3MHlNakE0TVRReU1ESXdORGRhTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXVMTG8rMHlETXM0ZDBGMkgKZ0RlcjI2OGJ5cGpnaE8wUWcxZ21pNGZIT1BWU01QNEpkeDdZOU5Ha0tVUXlUU0xyTGI5U05ET29wVHprYUp2dQo4V1JZazRUL3BGR2ljQ3VoSjhoT3ZqNGpPeU0xMk82RStzSFJjK21rdVdPZnYwTTJYZ3QxTHA0b0x3NGcwQVl1CklKTHMwVU9lNjFEV3FOdEFhZEY0SlNxUzNPa1J3OVFNQ25VMXM4TUFPM2Q4bXlpd2VqTjhpbERuTithMjJvaS8Kc1hzSnBNWE16WnNmSWlvTlBNUzA1ODdQWE5RaW1VcmdvUk5yVFplRmxrN0NKWVgyUmlvVHdHSmtDS0ZvQkRPSwpaMHR0bk5MQWY1NCs5Zi94bzBjck5wanBIazFNZTg3ZDh1Q2lxYmpmL1lXcGRrNlR2N0tqcFBYb2JLdEUvdlZjClN1eExHUUlEQVFBQm8xWXdWREFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RBWURWUjBUQVFIL0JBSXdBREFmQmdOVkhTTUVHREFXZ0JSUXlWYkxCNm9tWURxbVVialJ4c2NJSUtCVApOekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBRWxvaHpHK3RsK1NvdDBXLzZvQWZYVC9PdjlFS0E2N2hCbXZtCjBRQm1EZmI1VnZOelRPbkx4ZGhHcjlTbDhSTUlma2Zsei9YUDdRNjExeGYvdmF6cE1kS1h4NkdFOGpNSC94dlUKd0NXbFVSczJJbk5RUGFwRW44VmlXcDVqSWZzVzZCcFNPM24vMVZJb0VkUUVQUG5OM3dzS21RTXpmU0h3Qk9EZQp5RWZCV045NzgramhmRllaVnVabEoramova09kOHFsaE5VZlFZaEpjaEJoQUszaDVocmoyVWQ1L2o5VGZtVDVxCmxMb2FtVzdKcGgzNGlHYTdOYTJ4NnNDa2o1aFJ1bkVJRXpDWVdqYWxMR1NxYlRwUEhhaDVldDNuOTl4RlM2aFYKYWZJWXlBdm12U3orbXZJNFI3V0xjYk10QUVSQnBVUFpJUmM0YzA3a1RKVS81SG02a3c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBdUxMbysweURNczRkMEYySGdEZXIyNjhieXBqZ2hPMFFnMWdtaTRmSE9QVlNNUDRKCmR4N1k5TkdrS1VReVRTTHJMYjlTTkRPb3BUemthSnZ1OFdSWWs0VC9wRkdpY0N1aEo4aE92ajRqT3lNMTJPNkUKK3NIUmMrbWt1V09mdjBNMlhndDFMcDRvTHc0ZzBBWXVJSkxzMFVPZTYxRFdxTnRBYWRGNEpTcVMzT2tSdzlRTQpDblUxczhNQU8zZDhteWl3ZWpOOGlsRG5OK2EyMm9pL3NYc0pwTVhNelpzZklpb05QTVMwNTg3UFhOUWltVXJnCm9STnJUWmVGbGs3Q0pZWDJSaW9Ud0dKa0NLRm9CRE9LWjB0dG5OTEFmNTQrOWYveG8wY3JOcGpwSGsxTWU4N2QKOHVDaXFiamYvWVdwZGs2VHY3S2pwUFhvYkt0RS92VmNTdXhMR1FJREFRQUJBb0lCQUVRRzBUek5mMzBVNFhJLwpJSXNlOWhOaHVYQ3pRZTV6aWlOMk1pd3VCRGg4VXB0czFYdWtSdkJVem92TWJHSnd2QUlMZDNGMm5XVE91cW0wCjFScmZoS2hBMGc5cGFkUzZuUTZUL2p5ZmtrWlR2NTk0cWszWldSWENOa041NS9wLy9PUkNnQlI5ZC90c3pyVVAKc2FtWnM5T1hmazdaWlZhbitsOS9JU3MvTlB4YjBpSXJRQ0ZoNmNNKzAzUkVKWDh5MDhpOHZXbHVOMTZScmpwVgpBaDM4K3NWcU1wbHhmSmNGekVVZG00L3g5UjBuL3Z4UTVybDZDam9VdzcyTkxQRSthRjlWMDhFaUluZklRYjlpCnNTZ1huWTJCU0x5QWlpYUVsdEVIYzdob3F1cVh6TkR5NkI3bGRNNmdUQ3BIZ1hLc295VlpFWEtFcFRSbnpzUTkKRis3eHR1a0NnWUVBOWd1Rk8zdXRTUElvZ0lURG43L1ZlZEVzZ1F2WVYvUHFjWnhZTjVYNktRNVl4bWQ0ZGhCawpjUHh4cEMxSTZQSDhlQ3ltSlY5UUVQSmR1T0tXNkxiWExYY1ByNXBJZkx3VVRwdnVrMFp1aFRKYnBLVEhLbE5zCkFyclZTYlZRYmRYSXU3aDRqLzB5TitLbHhsNGpidzgzYzBsNHhFQktXcWc4Rkt6c2g2L1ZNeU1DZ1lFQXdDdjYKNE15RzIzL0hSTWJrSHdBdjNXMjhadEpkcDdiRkxSVkNmakR2dmJaQS9YT2FpL1pISW15NG5rRnV0RzU2b1pOdwp0YzB5MG1Qa0JkSWxrZzA1TVZIME12M3RrM09OR3E4TURLdTV2a0hMVUx5dmJmekN3UGZjMTRRVU0rVEdQZjBECmhzUU5HNWcvMlFHenJzUXZwaWhBTk5aRytPL3RtSmhVbUg0T09wTUNnWUVBd0JEWUxVbnJTRkU0aXJLWTN1QnEKTFpDNnMvWGlLUzVQNmVZSSswTkpKN2w2VlU2Nk96ZXFvSVIvMVpCQUpRK1piTm8xekdDdDZMeTVxclMrNXVTcgo3bUxOek4rY0REcnBneis0S2lGRjd4WVRjZC9yVlVBUHhjWEE3NnZwSUFSTmtUUjhjTEpPL0U4aDUwcmZVRGZKCnFtWkZMcldkRlUzVXNMTVlaUWMrWDQ4Q2dZRUF0QkZCemh5M2pMdXBtNitHRitwVDczY2czM1BrMy84cHVUbS8KaVlFUFU4T1FHQzJYdGVnNTlXN01leld5cHcwU2lZNGZRYXNhSVB3S3NNMmQrTUc5UXBLWmNLSnhXQVloUk15YgpUTkFvaHJjZDdQUXdxYTM3UzFlMXJwZ0xXaWpXL1VTMFpqWVVWalFPTjZnWmx2d3I3ZFN2ZlJML2c4bEY2QU5zCjJVcmN5Rk1DZ1lBNUZ6QlRXZ3Q4MlpuSTB4YXlSMzYwZjQ2MDUvNnZXbFR0eTBzZ0dKdVl1VGJnd2hXT0RNbTIKTnpUOE1aZ2xXZDVWQXJtUm42YmtvMjU3SWtTRVI4aXEranUzaHZXL1FNb0tLUXdxM0lYS2lyZnN1b0RoelRUTQo2Z2VubzNaK3ZuNi9XeWZWYm5aWFlCUU9TQmt0dUNHZ0xvSS9ob251RWc5UW1UaWwwajNqcGc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
