apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: nexus-local-path-pvc 
  namespace: devops-tools
spec: 
  accessModes: 
  - ReadWriteOnce 
  resources: 
    requests:
      storage: 100Gi

---
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: nexus 
  namespace: devops-tools 
spec: 
  replicas: 1 
  selector: 
   matchLabels: 
    app: nexus 
  template: 
   metadata: 
    name: nexus-template 
    labels: 
      app: nexus 
   spec: 
     containers: 
     - name: nexus 
       image: sonatype/nexus3:3.23.0
       ports: 
       - containerPort: 8081 
       volumeMounts: 
       - name: nexus-vol
         mountPath: /nexus-data 
     volumes:
     - name: nexus-vol
       persistentVolumeClaim:
         claimName: nexus-local-path-pvc

---
apiVersion: v1 
kind: Service 
metadata: 
  name: nexus-svc 
  namespace: devops-tools 
spec: 
  selector: 
   app: nexus 
  type: NodePort
  ports: 
  - name: nexusport 
    port: 8081 
    protocol: TCP 
    targetPort: 8081
    nodePort: 30002
  - name: nexusrepo
    port: 9090
    protocol: TCP
    targetPort: 9090
    nodePort: 30003 
