apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name }}-deploy
  namespace: {{ .Values.namespace | default "default"}}
  labels: 
   {{- with .Values.labels }}
   proj: {{ .proj }}
   app: {{ .app }} 
   {{- end }}
   release: {{ .Release.Name }}
spec:
 replicas: {{.Values.replicas }}
 selector:
  matchLabels:
    {{- with .Values.labels }}
    proj: {{ .proj }}
    app: {{ .app }} 
    {{- end }}
 template:
  metadata:
   name: {{ .Values.templateName }}
   labels:
    {{- with .Values.labels }}
    proj: {{ .proj }}
    app: {{ .app }} 
    {{- end }}
  spec:
   containers:
   - name: {{ .Values.containerName }}
     image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
     ports:
       - containerPort: {{.Values.containerPort }}    
   imagePullSecrets: 
   - name: {{.Release.Name }}-secret   