# This secret is for logging to Nexus docker images
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{.Release.Name }}-secret
  namespace: {{ .Values.namespace | default "default"}}
  annotations:
    strategy.spinnaker.io/versioned: "{{ .Values.spinnakerVersioned }}"
  labels: 
   {{- with .Values.labels }}
   proj: {{ .proj }}
   app: {{ .app }} 
   {{- end }}
   release: {{ .Release.Name }}
data:
  .dockerconfigjson: {{.Values.dockerconfigjson }}