apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Values.namespace | default "default"}}
  labels: 
   {{- with .Values.labels }}
   proj: {{ .proj }}
   app: {{ .app }} 
   {{- end }}
   release: {{ .Release.Name }}
spec:
  selector:
    {{- with .Values.labels }}
    proj: {{ .proj }}
    app: {{ .app }} 
    {{- end }}
  type: {{ .Values.serviceType }}	
  ports:
  - name: {{ .Release.Name }}-svc	
    port: {{ .Values.port }}	
    protocol: {{ .Values.protocol }}	
    targetPort: {{ .Values.targetPort }}	
    nodePort: {{ .Values.nodePort }}	